name: Model Requirements Validation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p data

      - name: Run Model Tests
        id: run_tests
        run: python -m unittest test_model.py -v

      - name: Generate Report
        if: always()
        run: python generate_report.py

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: test-results
          path: test_results.json
          retention-days: 90