name: Model Requirements Validation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create data directory
        run: mkdir -p data

      - name: Run Model Tests
        id: run_tests
        run: python -m unittest test_model.py -v

      - name: Create Report Script
        if: always()
        shell: bash
        run: |
          echo '#!/usr/bin/env python3' > process_results.py
          echo 'import json' >> process_results.py
          echo 'try:' >> process_results.py
          echo '    with open("test_results.json", "r") as f:' >> process_results.py
          echo '        results = json.load(f)' >> process_results.py
          echo '' >> process_results.py
          echo '    arch = results.get("architecture", {})' >> process_results.py
          echo '    perf = results.get("performance", {})' >> process_results.py
          echo '' >> process_results.py
          echo '    # Architecture Section' >> process_results.py
          echo '    param_count = arch.get("parameter_count", None)' >> process_results.py
          echo '    if param_count is not None:' >> process_results.py
          echo '        print(f"- Parameter Count: {param_count:,} {\'✓\' if param_count < 20000 else \'❌ Exceeds 20k\'}")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Parameter Count: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    batch_norm_count = arch.get("batch_norm_count", None)' >> process_results.py
          echo '    if batch_norm_count is not None:' >> process_results.py
          echo '        print(f"- Batch Normalization Layers: {batch_norm_count} ✓")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Batch Normalization Layers: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    dropout_probs = arch.get("dropout_probs", [None])' >> process_results.py
          echo '    if dropout_probs[0] is not None:' >> process_results.py
          echo '        print(f"- Dropout Probability: {dropout_probs[0]} ✓")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Dropout Probability: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    has_fc = arch.get("has_fc", None)' >> process_results.py
          echo '    if has_fc is not None:' >> process_results.py
          echo '        print(f"- Architecture: {\'FC\' if has_fc else \'GAP\'} ✓")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Architecture: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    output_shape = arch.get("output_shape", None)' >> process_results.py
          echo '    if output_shape is not None:' >> process_results.py
          echo '        print(f"- Output Shape: {output_shape} ✓")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Output Shape: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    print("\\n### Performance Tests")' >> process_results.py
          echo '' >> process_results.py
          echo '    device = perf.get("device", None)' >> process_results.py
          echo '    if device is not None:' >> process_results.py
          echo '        print(f"- Device: {device}")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Device: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    inference_time = perf.get("inference_time", None)' >> process_results.py
          echo '    if inference_time is not None:' >> process_results.py
          echo '        print(f"- Inference Time: {inference_time}ms ✓")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Inference Time: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    valid_probabilities = perf.get("valid_probabilities", None)' >> process_results.py
          echo '    if valid_probabilities is not None:' >> process_results.py
          echo '        print(f"- Valid Probabilities: {\'✓\' if valid_probabilities else \'❌\'}")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Valid Probabilities: N/A")' >> process_results.py
          echo '' >> process_results.py
          echo '    model_stability = perf.get("model_stability", None)' >> process_results.py
          echo '    if model_stability is not None:' >> process_results.py
          echo '        print(f"- Model Stability: {\'✓\' if model_stability else \'❌\'}")' >> process_results.py
          echo '    else:' >> process_results.py
          echo '        print("- Model Stability: N/A")' >> process_results.py
          echo 'except Exception as e:' >> process_results.py
          echo '    print(f"Error processing test results: {e}")' >> process_results.py
          chmod +x process_results.py

      - name: Generate Test Report
        if: always()
        run: |
          if [ -f test_results.json ]; then
            echo "## Model Validation Results" >> "$GITHUB_STEP_SUMMARY"
            echo "### Architecture Tests" >> "$GITHUB_STEP_SUMMARY"
            ./process_results.py >> "$GITHUB_STEP_SUMMARY"
          else
            echo "⚠️ No test results file found" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: test-results
          path: test_results.json
          retention-days: 90